site_name: 'python3'
site_description: 'Main documentation for the python3'
repo_url: https://github.com/digvijaysingh54/python3
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'